### ISSUE TITLE
Training guide

### ISSUE THREAD

**Issue by stephenivy07** [icbcbicc/PyTorch_EPLL#3]
Hi,
Thanks for your great work! I was wondering if you could provide a training guide. Thank you!

**Comment by icbcbicc** [comment]
Hi,

Although the Python training code works, sklearn is much slower than the Matlab version which you can find in [here](https://www.mathworks.com/matlabcentral/fileexchange/26184-em-algorithm-for-gaussian-mixture-model-em-gmm). In practice I use the Matlab code to train the GMM model.
